name: Do Not Submit

on:
  pull_request:
    branches: ['main']

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: chainguard-dev/actions/donotsubmit@1b32103f5aa389c31ab0be75a8edc38d7e4750d8 # main
