name: Do Not Submit

on:
  pull_request:
    branches: ['main']

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: chainguard-dev/actions/donotsubmit@be7b31a01af8ce7228fe901326f1d223fb788e14 # main
