name: Do Not Submit

on:
  pull_request:
    branches: ['main']

jobs:

  donotsubmit:
    name: Do Not Submit
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: chainguard-dev/actions/donotsubmit@8fa93a69e091d35d496b4af0a32d2e79c8d1ce00 # main
