name: Code Style

on:
  pull_request:
    branches: ['main']

jobs:

  goimports:
    name: check goimports
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true
      - uses: actions/checkout@v3
      - uses: chainguard-dev/actions/goimports@80013e908e778d79f1abf512b5b8770c19803b90 # main

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
          check-latest: true

      - uses: golangci/golangci-lint-action@v3.3.0
        with:
          version: v1.45.2

      - uses: reviewdog/action-misspell@v1
        if: ${{ always() }}
        with:
          github_token: ${{ secrets.github_token }}
          fail_on_error: true
          locale: "US"
          exclude: ./vendor/*

      - uses: chainguard-dev/actions/trailing-space@80013e908e778d79f1abf512b5b8770c19803b90 # main
        if: ${{ always() }}

      - uses: chainguard-dev/actions/eof-newline@80013e908e778d79f1abf512b5b8770c19803b90 # main
        if: ${{ always() }}

      - uses: get-woke/woke-action-reviewdog@v0
        if: ${{ always() }}
        with:
          github-token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: error
          fail-on-error: true
